# Generated by Django 4.2.4 on 2023-08-13 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foreign_id', models.IntegerField()),
                ('location_from', models.CharField(max_length=255)),
                ('location_to', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('new', 'New'), ('delivered', 'Delivered'), ('received', 'Received'), ('rejected', 'Rejected')], max_length=100)),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('datetime_changed', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
